version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "todolist-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    image: api:latest
    build: .
    container_name: "todolist-api"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "todolist"
      DB_PORT: "5432"
      DB_SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack
    volumes:
      - ./:/go/src/github.com/Shambou/todolist

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
